webtalk_init -webtalk_dir D:/VHDL_Projects/MCP23S08_switches/spi_MCP23S08_switches/spi_MCP23S08_switches.sim/sim_1/behav/xsim/xsim.dir/spi_MCP23S08_switches_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Sep 11 13:32:05 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211433687_1777503702_210713598_203" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6991da0a-c949-4bb3-9a94-97cb2dead16a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "dd61fa8b22734a4e935c7e96149a97af" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 3700X 8-Core Processor             " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3593 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "201250 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8828_KB" -context "xsim\\usage"
webtalk_transmit -clientid 617076875 -regid "211433687_1777503702_210713598_203" -xml D:/VHDL_Projects/MCP23S08_switches/spi_MCP23S08_switches/spi_MCP23S08_switches.sim/sim_1/behav/xsim/xsim.dir/spi_MCP23S08_switches_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/VHDL_Projects/MCP23S08_switches/spi_MCP23S08_switches/spi_MCP23S08_switches.sim/sim_1/behav/xsim/xsim.dir/spi_MCP23S08_switches_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/VHDL_Projects/MCP23S08_switches/spi_MCP23S08_switches/spi_MCP23S08_switches.sim/sim_1/behav/xsim/xsim.dir/spi_MCP23S08_switches_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
